version: '3.1'
services:
  postgres:
    image: postgres:13.6-alpine3.15
    restart: always
    environment:
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_DB: '${DATABASE_NAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
